version: '3.8'
services:
  resume-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-app
    ports:
      - "8501:8501"
    volumes:
      - ./resumes:/app/resumes
    environment:
      - PYTHONUNBUFFERED=1
