# Netlify configuration for Streamlit app
[build]
  publish = "."
  command = "streamlit run app.py --server.port=8888 --server.address=0.0.0.0"

[dev]
  command = "streamlit run app.py --server.port=8888 --server.address=0.0.0.0"
  port = 8888
